name: schad_pd1
channels:
  - defaults
dependencies:
  - blosc=1.16.3
  - krb5=1.16.1
  - snowballstemmer=2.0.0
  - functools32=3.2.3.2
  - requests=2.22.0
  - bzip2=1.0.8
  - liblief=0.9.0
  - prompt_toolkit=1.0.15
  - mpfr=4.0.1
  - path.py=11.5.0
  - ipaddress=1.0.22
  - dbus=1.13.6
  - jdcal=1.4.1
  - keyring=18.0.0
  - tbb=2019.8
  - gevent=1.4.0
  - sphinxcontrib=1.0
  - widgetsnbextension=3.5.1
  - bleach=3.1.0
  - rope=0.14.0
  - curl=7.65.3
  - qtconsole=4.5.5
  - zstd=1.3.7
  - ipykernel=4.10.0
  - mkl=2019.4
  - soupsieve=1.9.3
  - appnope=0.1.0
  - numba=0.45.1
  - urllib3=1.24.2
  - mkl-service=2.3.0
  - pandoc=2.2.3.2
  - sortedcontainers=2.1.0
  - colorama=0.4.1
  - ptyprocess=0.6.0
  - python.app=2
  - jsonschema=3.0.2
  - backports.functools_lru_cache=1.5
  - libxml2=2.9.9
  - singledispatch=3.4.0.3
  - zict=1.0.0
  - wurlitzer=1.0.3
  - mccabe=0.6.1
  - toolz=0.10.0
  - traitlets=4.3.3
  - anaconda-client=1.7.2
  - grin=1.2.1
  - zlib=1.2.11
  - libedit=3.1.20181209
  - lz4-c=1.8.1.2
  - llvmlite=0.29.0
  - pywavelets=1.0.3
  - pycrypto=2.6.1
  - pytables=3.5.2
  - et_xmlfile=1.0.1
  - get_terminal_size=1.0.0
  - entrypoints=0.3
  - bottleneck=1.2.1
  - send2trash=1.5.0
  - ncurses=6.1
  - xlwt=1.2.0
  - cdecimal=2.3
  - gmp=6.1.2
  - locket=0.2.0
  - nltk=3.4.5
  - babel=2.7.0
  - scandir=1.10.0
  - xlsxwriter=1.2.1
  - pyzmq=18.1.0
  - ipython_genutils=0.2.0
  - dask=1.2.2
  - pygments=2.4.2
  - pyparsing=2.4.2
  - libiconv=1.15
  - icu=58.2
  - tk=8.6.8
  - ca-certificates=2019.8.28
  - unixodbc=2.3.7
  - xlrd=1.2.0
  - pycosat=0.6.3
  - lxml=4.4.1
  - anaconda-project=0.8.3
  - pytest=4.6.2
  - greenlet=0.4.15
  - ruamel_yaml=0.15.46
  - pexpect=4.7.0
  - tornado=5.1.1
  - pyqt=5.9.2
  - nose=1.3.7
  - astropy=2.0.9
  - nbformat=4.4.0
  - cryptography=2.7
  - pandocfilters=1.4.2
  - wrapt=1.11.2
  - pycurl=7.43.0.3
  - xlwings=0.15.10
  - readline=7.0
  - kiwisolver=1.1.0
  - lzo=2.10
  - partd=1.0.0
  - setuptools=41.4.0
  - xz=5.2.4
  - libssh2=1.8.2
  - networkx=2.2
  - yaml=0.1.7
  - cycler=0.10.0
  - markupsafe=1.1.1
  - sip=4.19.8
  - glib=2.56.2
  - pycodestyle=2.5.0
  - traceback2=1.4.0
  - glob2=0.7
  - sqlalchemy=1.3.9
  - heapdict=1.0.1
  - gettext=0.19.8.1
  - gmpy2=2.0.8
  - libsodium=1.0.16
  - asn1crypto=1.0.1
  - jupyter=1.0.0
  - numexpr=2.7.0
  - zeromq=4.3.1
  - sphinxcontrib-websupport=1.1.2
  - py-lief=0.9.0
  - numpy=1.16.5
  - atomicwrites=1.3.0
  - scipy=1.2.1
  - qtpy=1.9.0
  - py=1.8.0
  - portaudio=19.6.0
  - pyyaml=5.1.1
  - statsmodels=0.10.1
  - olefile=0.46
  - pcre=8.43
  - importlib_metadata=0.23
  - libgfortran=3.0.1
  - pyopenssl=19.0.0
  - jupyterlab_launcher=0.11.2
  - mock=3.0.5
  - pylint=1.9.2
  - six=1.12.0
  - libcxx=4.0.1
  - scikit-learn=0.20.3
  - distributed=1.28.1
  - testpath=0.4.2
  - qtawesome=0.6.0
  - pathlib2=2.3.5
  - tqdm=4.36.1
  - contextlib2=0.6.0
  - multipledispatch=0.6.0
  - filelock=3.0.12
  - imagesize=1.1.0
  - jedi=0.15.1
  - terminado=0.8.2
  - defusedxml=0.6.0
  - funcsigs=1.0.2
  - libarchive=3.3.3
  - pysocks=1.7.1
  - pyodbc=4.0.27
  - ripgrep=0.10.0
  - certifi=2019.9.11
  - bkcharts=0.2
  - jpeg=9b
  - nbconvert=5.6.0
  - astroid=1.6.5
  - linecache2=1.0.0
  - mistune=0.8.4
  - future=0.17.1
  - numpy-base=1.16.5
  - pytz=2019.3
  - matplotlib=2.2.3
  - docutils=0.15.2
  - expat=2.2.6
  - blas=1.0
  - libpng=1.6.37
  - jupyter_core=4.5.0
  - hdf5=1.10.4
  - click=7.0
  - libcxxabi=4.0.1
  - jupyterlab=0.33.11
  - ipywidgets=7.5.1
  - jbig=2.1
  - flask=1.1.1
  - itsdangerous=1.1.0
  - bitarray=1.0.1
  - libcurl=7.65.3
  - sphinx=1.8.5
  - pickleshare=0.7.5
  - cffi=1.12.3
  - mkl_random=1.1.0
  - configparser=4.0.2
  - spyder=3.3.6
  - sqlite=3.30.0
  - pycparser=2.19
  - sortedcollections=1.1.2
  - pip=19.2.3
  - jinja2=2.10.3
  - cytoolz=0.10.0
  - unittest2=1.1.0
  - pandas=0.24.2
  - lazy-object-proxy=1.4.2
  - pkginfo=1.5.0.1
  - cython=0.29.13
  - freetype=2.9.1
  - unicodecsv=0.14.1
  - python-dateutil=2.8.0
  - idna=2.8
  - tblib=1.4.0
  - appscript=1.1.0
  - mpc=1.1.0
  - clyent=1.2.2
  - intel-openmp=2019.4
  - typing=3.7.4.1
  - beautifulsoup4=4.8.0
  - libffi=3.2.1
  - pyaudio=0.2.11
  - openssl=1.1.1d
  - attrs=19.2.0
  - boto=2.49.0
  - psutil=5.6.3
  - wcwidth=0.1.7
  - werkzeug=0.16.0
  - subprocess32=3.5.4
  - isort=4.3.21
  - ipython=5.8.0
  - fastcache=1.1.0
  - openpyxl=2.6.3
  - seaborn=0.9.0
  - more-itertools=5.0.0
  - cloudpickle=1.2.2
  - prometheus_client=0.7.1
  - pep8=1.7.1
  - ssl_match_hostname=3.7.0.1
  - bokeh=1.3.4
  - snappy=1.1.7
  - patsy=0.5.1
  - wheel=0.33.6
  - scikit-image=0.14.2
  - spyder-kernels=0.5.2
  - jupyter_client=5.3.3
  - chardet=3.0.4
  - backports.os=0.1.1
  - h5py=2.9.0
  - mpmath=1.1.0
  - pillow=6.2.0
  - mkl_fft=1.0.14
  - imageio=2.6.0
  - parso=0.5.1
  - ply=3.11
  - simplegeneric=0.8.1
  - anaconda=2019.10
  - jupyter_console=5.2.0
  - libxslt=1.1.33
  - enum34=1.1.6
  - numpydoc=0.9.1
  - zipp=0.6.0
  - pyrsistent=0.15.4
  - python=2.7.16
  - pyflakes=2.1.1
  - dask-core=1.2.2
  - sympy=1.4
  - webencodings=0.5.1
  - futures=3.3.0
  - libtiff=4.0.10
  - notebook=5.7.8
  - packaging=19.2
  - backports_abc=0.5
  - qt=5.9.7
  - msgpack-python=0.6.1
  - html5lib=1.0.1
  - backports.shutil_get_terminal_size=1.0.0
  - pluggy=0.13.0
  - decorator=4.4.0
  - python-libarchive-c=2.8
  - backports=1.0
  - pip:
    - autograd==1.3
    - brewer2mpl==1.4.1
    - lifelines==0.19.5


